### ISSUE TITLE
Better styling and page layout

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#4] opened 2020-12-08 08:49 UTC

**Comment by niconoe** [comment] 2020-12-08 09:20
@peterdesmet: I'll be interested in your help at some point (I first need to place more elements, and make it simpler to run on a dev machine)

**Comment by niconoe** [comment] 2021-08-16 11:45
Update: recently started a first round of visual improvements on my side, will ask for more qualified help later.

**Comment by peterdesmet** [comment] 2022-09-15 11:44
Duplicate of #46.

**Closed by peterdesmet** 2022-09-15 11:44 UTC
