### ISSUE TITLE
Add pop-ups to interactive map?

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/mica-dashboard#56] opened 2023-01-12 13:36 UTC
I just had a meeting with the RATO people. To work efficiently with the MICA dashboard, they would like to retrieve the more information from the map. Just like for the LIFE RIPARIAS early alert tool (see picture), they would like to browse through the map and select each observation on the map that interests them. This would generate a pop-up with a link to the original observation. There, they can find information about the location, time, date, etc. and whether it was a capture or an observation. Is this something that can be implemented? (or is it already and did I just didn't use the platform correctly?)

![image](https://user-images.githubusercontent.com/32466479/212080447-a62186e5-e0aa-430c-b144-2ceb31d289e5.png)

**Comment by niconoe** [comment] 2023-01-25 11:51
Good suggestion Lien, I hope I'll have time to do that soon!

**Comment by niconoe** [comment] 2023-01-25 11:53
This is actually a duplicate of #15.

**Closed by niconoe** 2023-01-25 11:53 UTC
Labels: enhancement
